# Generated by Django 4.1.5 on 2023-01-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_post_created_at_post_update_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publised_at",
            new_name="published_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
